### ISSUE TITLE
Incompatibility with "Ae2 Wireless Terminal"

### ISSUE THREAD

**Issue by Saereth** [Keksuccino/FancyMenu#698]
I'm running into a crash when using these two mods together and trying to open to wireless crafting terminal UI. I'm not sure on which mod's side the issue lies so I've reported it to both of you. If I can provide any addition information please let me know and I'll be happy to respond. 

**To Reproduce**
Steps to reproduce the behavior (e.g.):
Install a Minecraft 1.19.2 Minimal mod list

No customizations setup in Fancy Menu, all default settings
Setup a basic ae system with a wireless crafting terminal and try to open it. 
The game crashes with a divide by zero error. 

**Expected behavior**
For the screen to open and not crash

**Game Log**
Crash Log: https://gist.github.com/Saereth/8f65cdf663b2392fe41f49910e1fee60
Latest.log: https://gist.github.com/Saereth/a59eea5a7b46d54b136b23eb93f97baf

**Basic Informations (please complete the following information):**
 - OS: Windows 11 Pro
 - FancyMenu Version: 2.14.13
 - Forge/Fabric Version: 43.3.8
 - Minecraft Version: 1.19.2
 - Active Mods:

 ```
Forge 43.3.8
Ae2 12.9.9
Ae2 Wireless Terminal 12.9.7
JEI 
Jade
Curios Api
Konkrete 1.8.0
Auudio 1.0.3
Melody 1.0.1
Architectury 6.5.90
Fancy Menu 3.0.6_MC_1.19.2
```

Issue for reference:
https://github.com/Mari023/AE2WirelessTerminalLibrary/issues/243

**Comment by Saereth** [comment]
Addition info: This crash does not occur with Fancy Menu removed from the scenario, nor does the crash occur in any standard ae2 UIs with.

**Comment by Keksuccino** [comment]
Did you enable customizations for that screen? If so, please manually disable it by removing the section for that screen from the `config/fancymenu/customizable_screens.txt`.

Also try it with FancyMenu v3. Maybe it fixes the issue.

**Comment by Keksuccino** [comment]
Uhm.. your log says you already have FancyMenu v3 installed and not 2.14.13.

**Comment by Saereth** [comment]
> Uhm.. your log says you already have FancyMenu v3 installed and not 2.14.13.

It is yeah, fancymenu_forge_3.0.6_MC_1.19.2. Sorry, copied the wrong version when I was typing out the files. 

I did not enable any customizations at all while I was testing this. Deleted all fancy menu folders in config and the 2 folders in the root of the instacnce and let them all regenerate fresh. I also tried setting a customization with a universal layout and specifically blacklisting the crashing screen by id but that didnt have any effect either.

**Comment by Keksuccino** [comment]
Fixed/Added in FancyMenu v3.1.0!

**Comment by wiredwhiskers** [comment]
Hi! I seem to be encountering this issue with the crafting terminal in FancyMenu v3.4.0, AE2 v12.9.9, Forge 43.4.6, Minecraft 1.19.2!

https://mclo.gs/wwarAHK

**Comment by Retried** [comment]
Hi, the issue has returned and exists in versions from 3.4.0 to 3.4.4.

**Comment by RubberDuckyDJ** [comment]
I'm having this issue on fabric too

**Comment by ArtpokeBr** [comment]
I Can also Confirm that this is still an issue in Fancy Menu 3.5.0
